import random,os,sys,time
from waf.libs.color import *
from waf.libs.tools import *

def calc(y):
  module = modules("waf/modules/"+str(y))
  num = 0;
  for x in module:
                        # Prints6 only text file present in My Folder
        num = num + 1
  return num
def sem():
        print (red + '   }--------------{+} programmer [Amerr] {+}----------------{'+default)
        print (red + '   }--------{+} GitHub.com/Ameraraibia168/WhoAmi {+}--------{'+default)
        print ("       =["+basic_yellow+" WhoAmi V {   2.1.2   }                       "+default+"]")
        print ("+ -- --=[ {:02d}  exploits - {:02d}  auxiliary - {:02d} network    ]".format(calc("exploits"),calc("auxiliary"),calc("network")))
        print ("+ -- --=[ {:02d}  payloads - {:02d}  wireless  - {:02d} spam       ]".format(calc("payloads"),calc("wireless"),calc("spam")))
        print ("+ -- --=[ {:02d}  amerr                                    ]".format(calc("amerr")))
        print ("")

def banner_1():
        print (default+"                   mM@@MM@@MM@@MM@@MM@@MM@@@MMMMM@@@@Mm                     ")
        print ("       ||========mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm===========||             "  )
        print ("       ||        @MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm         ||       ")
        print ("       ||        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM@         ||       ")
        print ("       ||        @@MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM         ||       ")
        print ("       ||        @MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM@         ||       ")
        print ("       ||        @@MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM         ||       ")
        print ("       ||        @MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM@         ||       ")
        print ("       ||========@MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=========||       ")
        print ("       ||         /TT\\mMMMMMMMMMMFRAMEWORKMMMMMMMMMMMMm           ||      ")
        print ("       ||        (____)@MM@@MM@@MM@@MMMMMM@@MM@@Mm                ||       ")
        print ("       ||        |# W |                                           ||       ")
        print ("       ||        |# A |                                           ||       ")
        print ("       ||        |#_F_|                                           ||       ")
        print ("       ||        |_  _|                                           ||       ")
        print ("       ||        /|__|\\                                           ||      ")
        print ("       ||       /__\/__\\ The Hacking Framework                    ||      ")
        print ("                 ()  ()")

def banner_2():
  print (default+" -----+-----+-----+-----+-----+north+-----+-----+-----+-----+-----+-----        ")
  print ("           , _-\','|~\~      ~/      ;-'_   _-'     ,;_;_,    ~~-        ")
  print ("  /~~-\_/-'~'--' \          ,'      /  / ~|-_\_/~/~      ~~--~~~~'--_        ")
  print ("  /                         ,'    , '|,'|~                   ._/-, /~        ")
  print ("  ~/-'~\_,               . '      ,\ /'~                /    /_  /~        ")
  print ("         '|        '',\~|\       _\~     ,_  ,               /|        ")
  print ("          '\        /'~          |_/~\\,-,~  \          ,_,/ |        ")
  print ("           |       /            ._-~'\_ _~|              \ ) /        ")
  print ("            \   __-\           '/  "+basic_yellow+"WAF"+default+" ~ |\  \_          /  ~        ")
  print ("             '\ |,  ~-_       '/           |  /\  \~ ,        ")
  print ("               ~-_'  _;       '\           '-,   \,' /\/  |        ")
  print ("                 '\_,~'\_       \_ _,       /'    '  |, /|'        ")
  print ("                   /     \_       ~ |      /         \  ~'; -,_.        ")
  print ("                   |       ~\        |    |  ,        '-_, ,; ~ ~\\        ")
  print ("                    \,      /        \    / /|            ,-, ,   -,        ")
  print ("                     |    ,/          |  |' |/          ,-   ~ \   '.        ")
  print ("                     |   ,/           \ ,/              \       |        ")
  print ("                    /    |             ~                 -~~-, /   _        ")
  print ("                    |  ,-'                                    ~    /        ")
  print ("                    / ,'                                      ~        ")
  print ("                    ',|           ")
  print ("                      ~'         ")
  print (" -----+-----+-----+-----+-----+south+-----+-----+-----+-----+-----+----- ")

def banner_3():
  print (default+"                             _         "   )
  print ("                           _|  \______________________________________   "   )
  print ("                          - ______        ________________          \_`,  "   )
  print ("                        -(_______   "+basic_yellow+"WAF"+default+"      -=    -=        2933       ) "   )
  print ("                                 `--------=============----------------`  "   )
  print ("                                           -   -         "   )
  print ("                                                    -   -         "   )
  print ("                                           `   . .  -  -         "   )
  print ("                                     .*` .* ;`*,`.,         ")
  print (" Year-2023                       `, ,`.*.*. *         "     )
  print (" ________________________________*  * ` ^ *____________________________" )


def banner_4():
  print (default +"""                            _...----.                """)
  print (default +"""                          .'    .-'`                """)
  print (default +"""                        ,''--..;                 """)
  print (default +"""                       /       |                  """)
  print (default +"""               _______/________|_______               """)
  print (default +"""              `-----/// _\  /_ \\\-----`                  """)
  print (default +"""                .---./ / o\/o \ \.---.                  """)
  print (default +"""               <(_ /// \__/\__/ \\\ _)>   _.---.                  """)
  print (default +"""                '-. //    oo    \\ .-'  .'   .__`\                  """)
  print (default +"""             o    /// __..--..__ \\\   /       \`\|                  """)
  print (default +"""          o-'*'-o //| '\/\/\/\/' |\\  /         ; '                  """)
  print (default +"""          \*\|/*/   ;--.  ""  .-;   |   _   _  |                  """)
  print (default +"""         .-'---'-. / \|||-....(|||`\ |  (o) (o) |                  """)
  print (default +"""        /         \ /\           /\|/           |                  """)
  print (default +"""        |  .---,  |/  \         /  ;  '         |                  """)
  print (default +"""        | / e e \ |    '.     .'   |   '-.       \                  """)
  print (default +"""         \|  ^  |/       '---'     |              \_                  """)
  print (default +"""         ()._-_.()     T R I C K   |     .._.----/` \                  """)
  print (default +"""        ,/\'._.'/\. '  .           |    /   ``"-/||\ \                  """)
  print (default +"""       / \/     \/ \     O R       |   |            `7,                  """)
  print (default +"""      |  ^^_____^^  |              | . /// _          |                  """)
  print (default +"""      |oOO`     `OOo|  T R E A T   ; |' / |_) _       |                  """)
  print (default +"""      \| '._____.' |/             /  \-|  |_)/ \ _    |                  """)
  print (default +"""       |::         | '.__     __,;    `|     \_// \   |                  """)
  print (default +"""       |::         |     `````   |     |        \_/  ;                  """)
  print (default +"""       |::         |             |      \           /                  """)
  print (default +"""       \::.        /_____________|       ``'--..___/                  """)
  print (default +"""        '._______.' '-|   |   |-'                 |                  """)
  print (default +"""          |_ | _|     |   |   |               __.-;                  """)
  print (default +"""          \  |  /     /-._|_.-\                    \                  """)
  print (default +"""           \_|_/     /`'-.|.-'`\                   /                  """)
  print (default +"""     """+basic_yellow+"WAF"+default+"""  /--T--\   /    .'.    \'-..____.---':''``                  """)
  print (default +"""         (__/ \__)  \____/  \___/                  """)



def banner_5():
  print (default +""" ,                                                               ,              """)
  print (default +""" \'.                                                           .'/              """)
  print (default +"""  ),\                                                         /,(               """)
  print (default +""" /__\'.                                                     .'/__\              """)
  print (default +""" \  `'.'-.__                                           __.-'.'`  /              """)
  print (default +"""  `)   `'-. \                                         / .-'`   ('              """)
  print (default +"""  /   _.--'\ '.          ,               ,          .' /'--._   \              """)
  print (default +"""  |-'`      '. '-.__    / \             / \    __.-' .'      `'-|              """)
  print (default +"""  \         _.`'-.,_'-.|/\ \    _,_    / /\|.-'_,.-'`._         /              """)
  print (default +"""   `\    .-'       /'-.|| \ |.-"   "-.| / ||.-'\       '-.    /`              """)
  print (default +"""     )-'`        .'   :||  / -.\\ //.- \  ||:   '.        `'-(              """)
  print (default +"""    /          .'    / \\_ |  /o`^'o\  | _// \    '.          \              """)
  print (default +"""    \       .-'    .'   `--|  `"/ \"`  |--`   '.    '-.       /              """)
  print (default +"""     `)  _.'     .'    .--.; |\__"__/| ;.--.    '.     '._  ('              """)
  print (default +"""     /_.'     .-'  _.-'     \\ \/^\/ //     `-._  '-.     '._\              """)
  print (default +"""     \     .'`_.--'          \\     //          `--._`'.     /              """)
  print (default +"""      '-._' /`            _   \\-.-//   _            `\ '_.-'              """)
  print (default +"""          `<     _,..--''`|    \`"`/    |`''--..,_     >`              """)
  print (default +"""           _\  ``--..__   \     `'`     /   __..--``  /_              """)
  print (default +"""          /  '-.__     ``'-;    / \    ;-'``     __.-'  \              """)
  print (default +"""         |    _   ``''--..  \'-' | '-'/  ..--''``   _    |              """)
  print (default +"""         \     '-.       /   |/--|--\|   \       .-'     /              """)
  print (default +"""          '-._    '-._  /    |---|---|    \  _.-'    _.-'              """)
  print (default +"""              `'-._   '/ / / /---|---\ \ \ \'   _.-'`              """)
  print (default +"""                   '-./ / / / \`---`/ \ \ \ \.-'              """)
  print (default +"""                       `)` `  /'---'\  ` `(`              """)
  print (default +"""                 """+basic_yellow+"WAF"+default+"""  /`     |       |     `\              """)
  print (default +"""                     /  /  | |       | |  \  \              """)
  print (default +"""                 .--'  /   | '.     .' |   \  '--.              """)
  print (default +"""                /_____/|  / \._\   /_./ \  |\_____\              """)
  print (default +"""               (/      (/'     \) (/     `\)      \)              """)


def banner_6():
  print (default +"""                        ,mmmmm,            ______     _________              """)
  print (default +"""                        @ooooo@,         / /. . \\   /./-----\.\              """)
  print (default +"""                        @0m0m0Q@        / /. . .`,\\>./,  ,  ,\.\              """)
  print (default +"""                        @0X00X@@       | |. . .  |:|\|   ,  ,  |.|              """)
  print (default +"""                     ____@0m00@_____   | | . . . |:|X| ,  ,  , |.|              """)
  print (default +"""                    @@@op(oboy)pop@@Ok | |. . .  |:|\|   ,  ,  |.|              """)
  print (default +"""                   @@@@opopopopop@@@p@@| | . . . |:|\| ,  ,  , |.|              """)
  print (default +"""                   @@o@@opopopo"""+basic_yellow+"WAF"+default+"""@@op@@,|. . .  |:|\|   ,  ,  |.|              """)
  print (default +"""                   @@o@@popopopopopop@o@@| . . . |:|X| ,  ,  , |.|              """)
  print (default +"""                    @@o@@mmmmmmgogogo@oo@|. . .  |:|\|   ,  ,  |.|              """)
  print (default +"""                     @@@@@@@mmm'ooo@|@oo@| . . . |:|\| ,  ,  , |.|              """)
  print (default +"""                      @oooooooOOOO@"  @o@|. . .  |:|\|   ,  ,  |.|              """)
  print (default +"""                      @OoOoO@OoOoO@   @@@| . . . |:|X| ,  ,  , |.|              """)
  print (default +"""                      @oooo@@@oooo@   @@@|. . . .|:|\|   ,  ,  |.|              """)
  print (default +"""                     .@@@o@@@@ooo@@  ,@@}| . . .//  \\_________/.|              """)
  print (default +"""                    .@@oo@@@@@@ooo@. "@@'|. . //     \==========/              """)
  print (default +"""                   .@ooooo@@@@@oooo@      \ //              """)
  print (default +"""                   @ooooO@' `@@ooo@|              """)
  print (default +"""                   @oooo@'   `@oooo@              """)
  print (default +"""                  @ooo@'     `oooo@|                    """)
  print (default +"""                  @oo@@'      `@oo@|                    """)
  print (default +"""                  @o@@|        @@o@,                         """)
  print (default +"""                  @@@@:        @@o@|                              """)
  print (default +"""                  @@@@:        @@o@|                        """)
  print (default +"""                  `@oo:        `@@@:              """)
  print (default +"""                  /@@@)        /@@@)              """)
  print (default +"""                (@@@@/       (@@@@/                        """)

def banner_7():
  print (default+"                .-:::/-.`        ")
  print ("               /:`     .:/               ")
  print ("       .:::---:/-        -o::-`          ")
  print ("      ./                  `  `:/         ")
  print ("  `/::/`                       +`        ")
  print (" `o                           `o-`       ")
  print ("  -/-----:::-                   .-/`     ")
  print ("            .:::::+/`.:::::::::::::`     ")
  print ("                  `...`                                                .:://`"   )
  print ("`.-::::::-`                                                        -:::.`  `/:"   )
  print (".:::::--..-:::::-.`                                           .-:::`        `:o`"  )
  print ("       `.--:::--:---:::--`                                -:::-`     `---:::--` "   )
  print ("               ``.-::::::::::::-``                   `-:::.  ``-:::::-``  "   )
  print ("                        `.-::::////:::-.``.....` `-:::..-::::--`          "   )
  print ("                                `..::://s:..//--/s/:::-.`                 "   )
  print ("                             `...-:::/::oo:o.-+-:so+///:::--..``          "   )
  print ("                  `.:--:::::--..`.:-:::-.` o`::`  `.---:::::/+/:::::::--:.``  ")
  print ("           .+o///-.```    `.:::::.`   `.://o/+////:``        ``.-:::::::----:/o:  "   )
  print ("             `.---::::::::-.      .:/+/-`         -/////:`              `.--:-  "   )
  print ("     -                         `/+/.           .-::/:-::+s+++-`    "   )
  print ("    oy:                      .+/`       `.-::://:`:`      ---/++/` "   )
  print ("    s:s  `:::.              +/`    .-:::-:-/-/` .-:`       `:.---o:"    )
  print ("    o:s.-/   :/            +/ `-:://--:::` :`/  `:.-      ``./-::`o/ "   )
  print ("    //.y+     /:  `.-://///::::. .-   ..:` :`/   :.:-.--...``  ``.-s/- "  )
  print ("    :+ y- `.://o///:.``    ::    :`   ..:` `:.-   /``   `........   `:o`"  )
  print ("    .o`h+//-.       ```...-o`    -` ``--.--.` :```:.  .:.`     .:  `--h. "  )
  print ("    -o/s///////o/////::-:h-s-    `:..`         ..``   .:`   `.-. .-.`+/ "   )
  print ("    o/y::     -/        +/`yy`                         `.---.  .+/:++. "    )
  print ("   `s++ /-   .+`       `s`s-.s.             .::::o`   `.o---o+//::.  "    )
  print ("   ++s`  :/-::`        /o+:  `/+o+/::--.---+:+ysoo/////:y`  s+     "    )
  print ("   so-                       -/+/::-...../o+o+/-        :+//s-+-  "    )
  print ("                            /:/:   `.---:o/+/o+-//`         `//-/` "    )
  print ("                         `-o+/o::/++//:/::::`  -/:+-          .+.+` `:++` "      )
  print ("                        .o::::----.`             :/:/   ``.----+++s+++: "     )
  print ("                                                 :+/o+so+///:::-...``"   )
  print ("                                                 -:-.` "    )

def banner_8():
  print (default+"                                        "   )
  print ("                                   `-::-..:+/-`                           `"                   )
  print ("                                 `:/-`.-//:::+ys``                      `-`"                       )
  print ("                                `:--::..-:+ohNNm-                       `+//+:"                      )
  print ("                                /s+-`..sy+::ohy/:/:..-:-               `/+.`/o "                    )
  print ("                     ``-::-----:so:+ydhy.`/y:/.`.oo.` `:.           ``--/s/+/`"                    )
  print ("                      :ys:.-:/./dmNNh/ys `-/-/- `:s-   .:         .---`---`` "                    )
  print ("                      oos:   .-/ssyhN++y`::.:+.` -o-   `+      `-/-+:--` "                       )
  print ("                     `o//+` `-.   `.+:+s-..:+-  `-/`   -/    ./+:-+ddhy. "                      )
  print ("                      +:/o` .:`   `./.`:/:/os:..-+/::--/```-+o--+dNNd+. "                      )
  print ("                     `://+``:o:.`//::` `:-+d+++/o+::-//``:o+:-odNMmo.` "                      )
  print ("                      .:+o:...-+.y/ -/```.+:`+/`:    `:oo/-.+mNMMy:  "                       )
  print ("                     ``-:y`   -/.//-///.-///:/:`/` ``:+o-+:::NNm+` "                        )
  print ("                      .+.+-   -/`/.--`.s/. /`-:`+`./+/-o./:/+hy-`"                         )
  print ("                      -/`.o`  ./`+.   -o` ``.:/.s.+++y:.:.:/s/`` "                        )
  print ("                      -o-.. `.-: +-   `+ `:/+/:-oy+/mNs`o/y/`  "                         )
  print ("                      -s+.  `-o/ :/   `o:+/--/+o//oy/dy/+/+` ` "                        )
  print ("                      :s/`   `.: `s``-/s:.``-+//sdh+-os-`:: "                          )
  print ("                     `+-`     `.` +./+:+``:/:/ymy/:+oohh/+`"                           )
  print ("                      :`   ```./-`.://`+:::odmy/:o++o/+yh/ "                            )
  print ("                     `--``-----os.:+/+/::sdmo/++-:+:/o+/ss/ "                               )
  print ("                      -o::-:::/+sosys/:ymdo/syy.`:/::-oo-.+- "                              )
  print ("                     `.o+-`  `   `:o:+mhoohs:+s.-/-/.-.`-:. "                              )
  print ("                      `:o//:`       .:/+s+.`/o:s+/:++.:+. "                               )
  print ("                       ..`-//+:.``   ````  `-o::`   :+-/`"                               )
  print ("                       ````.::``.---:-`    `.++//.-/:..-` "                             )
  print ("                        `:/-` ``   .::/-..-://``..`+:::``"                              )
  print ("                        ::`       `.`.-.+:.::      //`"                                )
  print ("                       -:`       `-  `+/-/--` `.:-./+."                                )
  print ("                       `:-      -+.  ` /.``   `o-:--+s` "                             )
  print ("                         `:- ` :o-   ``/.      o ` ``:: "                            )
  print ("                          ++:-++.`  .:/:/:`    +`    .:` "                          )
  print ("                         ./`````   `//``/o+`   ./  ``--` "                         )
  print ("                        `+`       :-.`  .o:    `/---//` "                         )
  print ("                       ./-        :+.   `/-`    ``` -+` "                        )
  print ("                      `/-          .:.  ``+:`       `/. "                       )
  print ("                       //           :/`   o/       `-:` "                      )
  print ("                       .s:         .+-   `:`       `//."                      )
  print ("                        -o.    ``  `/.   ..       ` ./- "                    )
  print ("                         `o` `-o:--++`   `-.   -`   .:-`"                   )
  print ("                          ::`:o/:--o/`     /-.:o///++-"                    )
  print ("                          `:ydh:`  `/:     -y:--ydsoo`"                   )
  print ("                           .ymhs:   -o.    `/. .ymyds "                  )
  print ("                           .osdms.`  :s.`  `-/`//dyms` "                )
  print ("                          `-:++hd/`  `-+:.  .+::/dsm/:` "              )
  print ("                          `:/o/+d/`   `-sm: `+//sydN-. "              )
  print ("                           `.`-+o/`  .omNMo `+/./+hM:  "             )
  print ("                          ``-+y/:. `-hMMNh- `+-.-:/oo:-.` "         )
  print ("                      ```.---.`  ``+dmyh/`  ./-`://:-:ohy+."       )
  print ("                      `-ydso+///osmNd:``    ::``::/sdNNMMNms-`"   )
  print ("                      `oddhhddddddy/`      .dmhdmNMMMMMMMMMMm."  )
  print ("                         `     ``          `oyhhyyyyyyyysss+:`" )


def banner_9():
  print (default+"                                                                                  ` "   )
  print ("                                                                            ``./ "   )
  print ("                                                                       `.---:s:. "   )
  print ("                                                                 ```.-:-.```+.`  "   )
  print ("                                                              ``-:-/+`  `:/`    "   )
  print ("                                                             `-:--`   `+../.    "   )
  print ("                                                        .-/::-./      -+-`    "   )
  print ("                                                     .:/-`./-`-:`  `-:.`    "   )
  print ("                                                  `:+-`    .o/```.::`    "       )
  print ("                                                `:/--/  `-:-`.-/o.`    "     )
  print ("                                             ``-/.   ./-:-::-./-     "      )
  print ("                                         `.-::s/`  `-:///:.`::``   "    )
  print ("                        `            `.-:-../-.//.::/:-`:--/.    "      )
  print ("                    `.:os`` ``````..-:.``-::.--::-//` ```::`   "       )
  print ("          `-/----:--:+:/-::----..-+/` `::-::-``./:``-:-++.   "        )
  print ("        `-/-..--/-.--..---::----/-```-:.//. ``//.:::.`+-    "         )
  print ("      `-++.```.+-:/`         `::``-/-`//`  `:///-` `-s/   "           )
  print ("      `:::-:/:.//::`       `-/``:/.`:/`  `:s/:`   `::+` "          )
  print ("        `.:/.`-//:-`     `-/..::`.::`   -o+.   ` -/.+. "      )
  print ("            -/o:``.-::-`.++::. `///` `::-`    `-++/:.  "       )
  print ("              `-//. `-///+:` `//` `:+/.    `-o:.o-`   "         )
  print ("            ```.:://-`-+:  `:/`  ./:` `  `::./`--    "       )
  print ("   `:/::::::---.`   -/s` .//`  -/:`    .::` -: +`    "       )
  print (" `-dd:           `-/-././:`` .+:`    ./:`   o`.+`   "       )
  print (" `:y::::.      `./-` `o/`` -/:`   -+o:`    `+ :-    "      )
  print ("-::::/-`.://  ./-```//` `-o+.``.:/o:`      .:`+    "      )
  print ("      .//:/.-+s.``::` `-/:.-:o+:/o.        -:-:    "      )
  print ("-:::--.-:o/:+-`/++:-:/o/:--..`-/../   ``:. ::/. `` "    )
  print (".:::::/:` `.++y+:-..``      .+/+``-:` /:/:`/.o-:yo "    )
  print ("           `hm/``         .:-` -+``/. /:/-.+:+/+-  "     )
  print ("           `/++/:/::-```-+s`    -+-++` `. `+o/.`            ``.:/+/:-`   "      )
  print ("              .:/-.:/.::.:-      -s`.:`   ::/              .+hmmmmmmmho-` "     )
  print ("        ``      `-++/-```/.``     -:`--+: -:-            `-hmmmohmmmyhmd:` "     )
  print ("      `/.+.-/```.:/.`.///:oo-`` `.+//+os:+o-.`  `    ``  .sNdmms.dy+:ymmh. "     )
  print ("      :--y.o/+/://///+..-/o.+:////+/:/o+:+-//--://-:/-.:/::::/::-`..oymmd. "   )
  print ("      `.s:/s.o//+/+-o:/+++--/+:+-/--.s-+::/:/+++o/////:::+:/-://ymmh+mmm+` "    )
  print ("       `+```   `+./  `++:  `        `: ` `:/o.   `:/o.    `-yddmmmmmmmh/` "    )
  print ("               :/+.  -o            .:-    .:-        .-+syyys+:.        ."   )



def banner_10():
  print (default+"                              -..`...--.`     .`  "                    )
  print ("                     .:`    ./:--//::::/+++++o+-:/`  "                          )
  print ("                     .:o---:.````.:/oo/:://:/++:-`    "                          )
  print ("                     .:.:+/.     `   ./o::/s:.    ``     "                  )
  print ("                      --:os+    `h/  ` -s:./oo+:-::`  `:` "                   )
  print ("                       `:````  `+s:     `h: -/:::-...--/` "                    )
  print ("                       :.  `+---s-:      o+  :. `````.:` "                  )
  print ("                      --.`-+. `/-.-      o/  `s/-.`./+. "                    )
  print ("                      `o///- -:` -`     .y+   ::/-.`   "                      )
  print ("                           .+.  ``      /++:` `/:/+/---`"                      )
  print ("                          `/`         `--:y/:.  .:-`` "                     )
  print ("                 `        -. ````.... .-+.o/:-:```.:::--"                    )
  print ("              `::::.``` `--. ````      `/+-//----....``"                     )
  print ("             `o.`-+::---+-              .++//+:-`"                     )
  print ("             -////+:...-:/             .:. .--.`"                   )
  print ("           `-:/--/`.:-`  -.  `.-.`           `.--.--.`"                  )
  print ("          ./.o.`/::  .--````//:`                   `.-:.`"                  )
  print ("         `:``/`-:`+.   .---//`.`                   `.. ./++-.`"                 )
  print ("          .--:-::::/-`      `:-`            `        -. `/+s/:/."              )
  print ("            .::::`//-.        .:-.         .-        `-  :.`o:`+/`"             )
  print ("             ::-- ./:-          `.---...` ./.         `  -- .+. ./`"              )
  print ("              .+`  `/.               ``-:-`+             :. .//  ::"              )
  print ("                                         .+:            `:` :./  `+"             )
  print ("                                          --           `:. ----   +"             )
  print ("                                          --        `:--` -:`:`  .-"            )
  print ("                                           --`  ..-/.o: `./.:`   /."           )
  print ("                                            `:-..` -:`+/`/::`   `/` "         )
  print ("                                              `.-:-..:-./o-    /++`    ` "   )
  print ("                                                 `+/``-+y-    .s:o:.``:-`"  )
  print ("                                                 :/ `-:yo     :/-`-:::. "  )
  print ("                                               -o:`:--/y/:    :--:.```.`" )
  print ("                                            `-o+..:`-+`+./o.  `::--:/. " )
  print ("                                           `:+. .:`-+- `--:+/--..--.  " )
  print ("                                          .::`o:. /-`    `  `...`  "   )
  print ("                                        .:-:::s+:+/              "   )
  print ("                                       `-------..` "                  )


def banner_11():
  print (default+"                    :---.-:-----------:--:.```````````.....`....-/+oo/ "  )
  print ("                    `..--.+``:/:/ooooooos//so/////////+++++++++++++++y "         )
  print ("                       ./+.`:s:-:osssssss/`:/````````````````````....+ "        )
  print ("                      ://:/oss:-:shhhhhhho-/s-----------/.----........ "        )
  print ("                   ./::.`.-:ss:-:+oo+++oso:+o::---:----:`" )
  print ("                 .+ysoo-````.++:/syhhhhhh/.o`"       )
  print ("               .oyso+oyyo.```./:/o:-----/-:+ "      )
  print ("              /yyo+++++oyy/.``-/+o::--`.+-:. "     )
  print ("             +yy+++++++ooyys`/../o-``s:-:.  "     )
  print ("            /yy++++++syyo+/+-:.``:/`-s/-   "     )
  print ("           `yh++ooo+sys.    .--:::://:` "       )
  print ("           +yo++oyo+yy:        `````` "        )
  print ("          `yy+++++++yy- "                     )
  print ("          /yo+++++++yy: "                    )
  print ("          sssooo++++ys/ "                   )
  print ("          /+osyyssssso/ "                  )
  print ("              `` ```    "                 )

def banner_12():
  print (default+"                                                                       ```"     )
  print ("                    `.---------....--:++/:........`````````           `+o/  "    )
  print ("         ``````````.osyyys+++++/////syssssssysssso+so///+++:........../++/.`"    )
  print ("    .:://+++++++++/osyyyyssssyyysyyyyyoossssssssoo+so++++oso+/////////ooo+:`"     )
  print ("    -oooosssssoooo++syyyyssosyhhyysooooooo+/--......-.--....`````````"    )
  print ("    `ooosssssso+/-.`/ssso::`/oshyy/   `..`` "     )
  print ("     /sooooo+/-`    /oo:.----.:yhys`   "           )
  print ("     `+o+/-.`      -so+`      `oyyyo.  "          )
  print ("      `.`          .//-        .oyyyo-` "        )
  print ("                                `+yyso.  "      )
  print ("                                  .+o. "       )
  print ("                                    `"        )

def banner_13():
  print (default+"                           `.:+osyyyyyyhhyyyyyyso+:.`"             )
  print ("                      `-+syys+:-``            ``-:+syys+-`  "             )
  print ("                   -+yyo:.                           `.:syy+."           )
  print ("                .ohs/`                                    `/yho."            )
  print ("             `+hy:`                                          `/yh/`  "           )
  print ("           .odo.                                                .sd+`  "          )
  print ("         `od+`                                                    `od+`"          )
  print ("        :ds`      `:.          ``..----------..``          .:`      `yd: "        )
  print ("      `sd-     -ymy.       `.......`.. .. -.`.-.....`       .hmy-     -ds`"      )
  print ("     -ds`  :/-hMN/      `..`  ..`  .-  ..  -`  `..  `..`      +NMy-/:  `yh. "      )
  print ("    :m+  .hy.mNy:.    ..`....-.    -`  ..  `-    .-....`..    ./yNd.hh.  om-"     )
  print ("   :m/ `.dM:oo/ss`  ..`    .-`....--.-//os/.--....`-.    `..  `ys/o+:Md.` +m-"     )
  print ("  .m+ /+/Mh.omNs  `-`     `-      -``hd:-dMy`-      -`     `-`  sNd+.dM/o: om."    )
  print (" `hs`:N++Nsmdo.  .-      `-      `-  ``./mh- -`     `-`     `-`  .odmsN/+N-`yh."   )
  print (" /m. yMo:my:+o` .-..``   -`      ..    -o.   ..      `-   ``..-. `o/:ym-sMs .m/ "   )
  print ("`do `dMh-/sNm. `-   ``..--..```  -`    :-    `-  ```..--..``  `-` .mNo/-hMh  sd` "   )
  print ("/m.`.sMh:NMy.  -`       -`  ```..-....:NN:....-..```  `-       `-  .hMm-hMo.`.m: "   )
  print ("sh //.mymm/-` .-        -       `-     --     -`      `-        -` .-+Ndhm.+/ ds "   )
  print ("do sd`+mh./y` -`       `-       `-  ..+oo/.`  -`       -`       .. `h:-dm/`mo sh "   )
  print ("N/ +Ms.s.sM+  -.```````.-```````.:oy..+dd/..yo:.```````-.```````.-  oMo.s.yM+ +d "   )
  print ("N/ -mMs`sMm`  -.```````.-`--:+osdMMs  :dh: `yMNdso+:--`-.```````.-  .NMo`yMm. +d "   )
  print ("do .oMN/mN/-` -`       `-yMMMMMMMMM-  `ys`  :MMMMMMMMMy-`       .. `-+Nd/NM+` sh "   )
  print ("sh +-+Nymh y: .-        /mMMMMMMMMM:  -NN-  /MMMMMMMMMm:        -` /s`hdhm/-/ do "   )
  print ("/m./m:.yN/.Ny  -`       +NMMMMMMMMMh` :MM- .dMMMMMMMMMN/       `-  hN.+Ny./m/-m: "   )
  print ("`do`yMh:+:+Mm` `-  ``...yMMMMMMMMMMMh`/MM:`hMMMMMMMMMMMy...`  `-` `mM///:dMs`sh`"   )
  print (" /m.`oNMh-+MN.+..-..``  dMMMMMMMMMMMMhoMModMMMMMMMMMMMMh  ``..-`./.NM/-hMNo .m/ "   )
  print (" `hy``:hMN+mN-/m-.-    .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`   `-`-N:-NdoNMh:``yy`"   )
  print ("  .m+ +:-oddNo.mm-`-`  /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-  .-`:Nm.sNddo-/+ od`"    )
  print ("   -m/`yd+.-oh-yMm.`.-`oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo`-.`.mMs-h+--ods`+d-"     )
  print ("    -m+ :dNmy+:.mMs:s:.hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy.:s:yMd.:+ymNh: om-"      )
  print ("     .dy` -smMMmshN+:NhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdN:oNhsmMMms- `yh."      )
  print ("      `sd- ./-/oyhhNs:dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd:sNdhyo/:/. :mo`"      )
  print ("        :dy``ohys+++++:oymNMMMMMMMMMMMMMMMMMMMMMMMMMMNdy+:+++++syho`.yh- "      )
  print ("         `+do` -+ydmNNNNmhso/hMMMMMMMMMMMMMMMMMMMMh/oshmNNNNmdy+- .od+` "      )
  print ("           `+ds. `:/:----:+ymMMMMMMMMMMMMMMMMMMMMMMmy+:----:/:` -sd+`")
  print ("             `/yh/`-+ydmNMNmdNMMMMMMMMMMMMMMMMMMMMNdmNMNmdy+.`/hy/`")
  print ("                .+hy/`   `  `mMMMMMMMMMMMMMMMMMMMMd`  `   .+yh+. " )
  print ("                   .+yys/.` .MMMMMMMMMMMMMMMMMMMMMN` `./syy/.  "  )
  print ("                      `./syyyMMMMMMMMMMMMMMMMMMMMMMyyys/.   ")
  print ("                           ``-/osyhdmmNNNNmmdhys+/-`` "   )

def banner_14():
  print (default+"                          `.........`         "       )
  print ("                      ``-.``        ...`              "      )
  print ("                      -.              `--             "         )
  print ("                     -.`................-:`           "        )
  print ("                    `:--`           ``  .:-           "       )
  print ("                  ` .::---:---`  `--..--`:-           "      )
  print ("               ```  -:.-.``..::./:.....-`/-          `"     )
  print ("               `  ``::``-::-.`- -..--.` `/:-`       `"     )
  print ("                  .-.::::://::. -++//+:` +:-.    "        )
  print ("                    :`:`    ``:` -````   `y-:`    "        )
  print ("                   -..-.``--/:` -/-.`  `:s/`                    `` "      )
  print ("                   `:-``//../+:///``.:-.:o.               `` "           )
  print ("                    `.:``.:--:``-::::-  o.   "         )
  print ("                      .:  ``--.---:-` `s:   "         )
  print ("                       `-`   -`-`   `./o   "         )
  print ("   `                  ...--  `-:   .-:+:.`    "          )
  print ("```                `.-./.---../:..--:`+-`....`  "            )
  print ("              `.....`  /` `.--````.-  s.    `.....`   "             )
  print ("       ``......        ./`   .--.:.  `s`          `.......`    "           )
  print ("  `.-...``              /-  --:`:--` ./                  `..-  "            )
  print (" `-`  ``                :.-.. -/` `.-/.     ``              .-  "           )
  print (" ..  ``                 -`.:` ./     :`                      -` "          )
  print (" : `                    ..   `:-.   `:   `                   -`  "           )
  print (" :                      `-   .- :   -`                       `-   "          )
  print ("..                       :   -` -. `-                         :   "         )
  print ("-.                       -` `:  `- -.                         ..   "          )
  print ("-.                       `- `:   :`:                          `-   "          )
  print ("-`                       `: -`   --.                           :   "         )
  print ("-`                        :`:    ::                            :`  "         )
  print ("-`                        `:-   ./.                            .-  "         )
  print ("-`                         /-   :/                              :  "        )
  print ("-`                         ./` `+`                              :  "         )
  print ("-`                         `::`::                               -` "        )
  print ("-`                          -:-+`                               -` "        )

def banner_15():
  print (default+"       :-:::::::::::::::::::::::::::::::::::::::::::-:  ````.``````````````"   )
  print ("       ::.`````````````````````````````````````````.:/ .    -      `.     .`"   )
  print ("       :/`                                         `:/ .````--.....--....-- "   )
  print ("       :/`   WhoAmi{framework}                     `:/ .   `.`......-.....-"   )
  print ("       :/`                                         `:/ .   `..............."   )
  print ("       :/`                                         `:/`.   `` .`````.`````."   )
  print ("       :/`   github{amerlaceset}                   `:/``   `` .`    `    `."   )
  print ("       :/`                                         `:/``   ``  .    `    ``"    )
  print ("       :/`                                         `:/.`   .` ```  ``    ``"    )
  print ("       :/`   versions{2.0.0}                       `:/.`   .`...----------` "   )
  print ("       :/`                                         `:/.`   .  ` `````````."    )
  print ("       :/`                                         `:/.`   .             ."     )
  print ("       :/`                                         `:/.    .             . "     )
  print ("       /:-`````````````````````````````````````````--/.    .        `   `. "     )
  print ("       --:--:::::::::::::--::-----::--::::::::::::::-/-`   .        `   `` "    )
  print ("                           `-     ..            ````````` `.        `   `` "     )
  print ("                  ````````````-     `-```````    ````     `.``        `   .`"    )
  print ("               -:.............    `-.........``   `````` `..````````.```.  "     )
  print ("              ``-----------------------------:-       ``..`   "        )
  print ("   ```````````.`.`....`.`......`............`..`.```.``.`.        "        )
  print ("    ..o/o+++++/o/+/++++/o+o++++++++o+////////:/+/o/o++o+-.``````..--.` "     )
  print ("  ``/+//o++o+s+o++o+o+o+oo+o+o+oo+o+/-/--``..-:/oo+s/s+o..   ..-...` .`"    )
  print ("  .`o+/++o+oo/o/++/o/+/++/+/+/+o+o+o//+-.-:--.-//+/o++o.:``   ``.`..  . "  )
  print ("  ../:///::/:::////////////////////////--::-:---:::::::::.-     ```.```"   )
  print (" `.`````````````````````````````````````````````````````` `-.......``` ````"   )
  print ("                                                           `.......`.`````.`"   )


def banner_16():
  print (default+"                                         "         )
  print ("            `      ```................```        `     "    )
  print ("        ``..---+o///++++/:---------.-:://////:-.-:.``     "  )
  print ("     `.-///::-..`                          ``...::-/+::-``  " )
  print ("    -oo:.`` ` `  ``       ```````````      `       ``.-:+o-` " )
  print ("   .o+`:///-.```...:///+++oo++ooo++///+++/--`` `-://o:` `:s:` " )
  print ("   -o-`----/+..s+/--:/sy/:+s-.`.````-sysyhoos:`.+/-..``  `/+.  " )
  print ("   :o.     `.:+m. `` `+/` `ho.``````-+. -o:`+hs:-.``  `   .ss:-`` ` ``"  )
  print ("   -s+`.-//o//.:yso+ooho`  +sosssoo/+o. .os++my-/o++:---..+o--:++/` "     )
  print ("   `/hy+/-.```-odh-`...`  ` ``````````  ``.../dso-..-:++/+hys++-+Ns:.`  "  )
  print ("    `:yo///+s+/-h:    `.:///+o/://oo/:.`  `.``s/.-++so+//oo.  .--++:+o-`  " )
  print ("   `  `.:::-` `+o   `-+ymdy/.oy/y++o-+so:`:o: :y  ` ``-:-.`       `.::/+-`` ")
  print ("         `` ` :y`  ./o/+y+/h/hssmyymyso:++.    d.                   `:+:++. " )
  print ("          `  -y.  `/+/ho+dmy+---:+hmdyo.`/o.`  s/                     -o/:/. " )
  print ("          ` .d.  `-h-`:/oy:`   `  `-ssoso:+/`  .d`  `                  .o+++`"  )
  print ("           :y- `  -h-`/ssh/` ` ` ``-sds/s/:/.  `s-                     `-+/+- "  )
  print ("          -y:` `  .o+.+symms/-`.:+ymdo-.``+/` ` :h   `           `````` .+/+/` "  )
  print ("         -s-`   `  .++syoshohhsmNhho+o. .++``   `y:               ys+ho+o+-+- ")
  print ("        -o-     `-- `-ohd+``so/hs+h/-.:+s:`      :y`       `.:--  -o/sys/:o/`" )
  print ("       `o/`` ```o/+``` `:+++:/++oo+/oo/-`        `h:  `.```y+.-sy:.:yssy/:``" )
  print ("       .o-   `````````.`..`...----.```           `:+`:oo/.`:+:-/sso/+oo-`")
  print ("       +s.  ./oo+:://+++++/////::-:/++::-.``     `:d-+:-ho../syy++o/-.`")
  print ("       oy.  .:..```           ` ````...::://++/.  -doss+osoo//+:`"    )
  print ("       os.  `                             ``.---` /mso+o+:-:-.``"    )
  print ("    `` -s:`                                    ```h/--.`"           )
  print ("     ```:o/-.......`````                         -m- "             )
  print ("         `---:/+oooo++++////////+++o++/:------:/oyo`"             )
  print ("                    ````...............`"                        )


def banner_17():
  print (default+"                           `                                                      "       )
  print ("                  :/      /d`                        ``.-::::-.``      `                  "      )
  print ("     .`     os    os+``.``y:/                      -+ssso+/++osso+os+/oyy-     ``         "       )
  print ("     yo`   ++s    -ooysshh+do::-.`               -oh+.`        .:/+//+` -ys/////ys.```.-:. "       )
  print ("     +o+/.-s.s`    /y+yysmomo:.+d+             `os+`     `::.`     -o/o` `o-    `s+:::--.s. "       )
  print ("      -yysy++o/:. :s`.shhoss::s`:o.            +h:       o:.-//o    -o:+  :+     `s.     // "       )
  print ("      :y+ydy+.`./+:++ `:yssy` .s.ss           -ho    `/oyy+///:y    `y`s  .o      +:     :+  "      )
  print ("     -s``:/syy`   .yy//yNh.`   //-y-          :d/      `s/hoo+sys:   s-s  .o      +-     o-  "       )
  print ("     `s.`ysohm-    +o/+ooy.    `y++`          .mo-:-  `-yoy:-dy:-/`  s/+  :+     `s`    .s`  "       )
  print ("      ++--ydmo`   /o.s.s./:     dh.      `.:+//yyssso/yss/+oy.o+-   .ys. `s-     +/.   .s.  "        )
  print ("     `ys+sms.++` `/o+++sod:     :`:///+oyys+//+oy/+y-:s:s``s.-o/y  .so:``o:     -so-  .s. "          )
  print ("     .s-/.y.  /+   /hs+h/yo..`     .:/+y.       `/hoyshsh/h+ys`// `y++  .+`    `s-:  .s. "         )
  print ("     `:ooooo--:d+oyo/ods-.-:/+o+ooys++:y-..`..-///ss:od+y`-+odsyy s:y   `.:sso+/+`  .s` "           )
  print ("       `/+//ooh/s.: ` /y-..-----..`   .y--/:-.``  .s  +mhyyyd/--s.y:+    `o/o.oos`  o- "           )
  print ("          ``  o:`:+  -+h/  `s   `y`   .s  .s.     oo  // ``-dhys+od:h/////o++/o+o///oo`"            )
  print ("             /yy/+.`-os.s.`+/   `y`  `s-   .s`   .m/  +s+/-..ds.:hhss+:+h+/o.  .//:`/+ "             )
  print ("            :h/:++sy:-s`-hy. `///-  `o-    `/+`  .h+` +sosss`y+/+oo  .shdyy+s``yyyhho`"             )
  print ("            sy.`s- ./h-`hy..oo++syo/+d+o//+s:/+///:so .s.--o///+/o. `s/osh-o+:+ssshy- "              )
  print ("           .s.y-`o+++s--y.++/h:-s/s. s-/+..o`   .s:ss. +do+hs+//::///ss+dd/o//s+ydo/: "              )
  print ("          `s.-so/:-.o-+y-yo+/os-s..++.y.++.s-   /+o..+/:sy:--://////oshoddy/o:sodd:o- "               )
  print ("         `o-`s. `..-:.s.+s:-/-+d.  :o-yo:++`   `s.s`  `-//`         :+yy/ss:s`s+Ny:s` "               )
  print ("        `s- -y`     `s- :+-/os/h``++`so.-h.   `+/++                 .s+ysoo+` :o//o. "               )
  print ("       .y:..s.     `o-  .d-`s//:`-+///://.   .y+/o`                  `///o:    .-.  "                )
  print ("       `.----      -o/::+/                   ````                                  "                  )



def banner_18():
  print (default+"                           ````..``` "                                    )
  print ("                      .:osyyyssoooooosssoo/. "                                         )
  print ("                 `/oso:.``             ``-/+o+- "                                     )
  print ("               -ys/`                         ./s+`"                                  )
  print ("             .sd:`                             `/h+ "                               )
  print ("            -dh`                                 -hy`"                             )
  print ("           .dd.                                   -ms"                            )
  print ("           +M/ -:                               :. oN."                          )
  print ("           yN. yy`                              hh`-M+"                         )
  print ("           sm. +s                               yy .Mo"                        )
  print ("           /N: .m-                             /N/ /M:"                       )
  print ("           `hy` hy       `            ```      hh``hh`"                      )
  print ("            -ds`sd``:oyhhdhy+`     .shdddhs+-  do.yd. "                     )
  print ("             .yhdy`yNMMMMMMMN:     oMMMMMMMMNs hmhs.  "                    )
  print ("     ..`      `sM/`hMMMMMMMMm.     -NMMMMMMMMh +M/       .--` "           )
  print ("   `yhyh/      -N. -hMMMMMMd:  ` `  /mMMMMMMd- .No     .shhmo "          )
  print ("   :M+`-ho`    :d`  `/yddh+. `+h.y/  .+hmdy/`  `No    -dy``ym."         )
  print ("   .sy`  .yh+-.`:N:     ``    oMN:NN+    ``     /N:`./shs`  `sh-"      )
  print ("  `sdo`     ./oyyohh+/-.`     -NMN:mMN`     `.-/shysyhs/.     `smo`"          )
  print (":mh/://++/-`  .:osyNMdho-   -NNy`hNm`   -ohdNhso/-.  `-/++/::+mh`"           )
  print (" .::::::/oyhy/.   .+NymMN+   :/` `:-   +NMh+m:`  `-+syso/:::::-`"           )
  print ("           .:oyy+-..hy/NMm.``````````.-mMM-+s`.:oys/-`"                    )
  print ("               `-+ssmh`dMs++/:o-o/+/+o:hMy hhoo/-`"                       )
  print ("                  `:dh oMssoo+y.y/o/+o/sN:.ms`"                          )
  print ("               `/shyhm``+os+//o.s:s:/+oo/ oNssy+:.` "                   )
  print ("     .::::::/oshs/. `ds`  `-/:+/+/+::.`  :Mh` `:oyhyo:+++/- "          )
  print ("    :Ndooo+/:-`  `./odmy-`             .oNNdo:`   `.:/+ooohs "        )
  print ("     .ym+`     `:ohy+:``/hho/-.`````.-/sdd+`./sys+-`     `+Ns`"      )
  print ("       .yy`  .yds:`       `:+ssyssssso/-`       `.+hh.  `yh/. "     )
  print ("        :No -ds`                                   `od. oN. "      )
  print ("        `ymhd/                                       /dhms "      )
  print ("          ``                                           `` "      )

def banner_19():
  print (default+"                                            ````````````  " )
  print (default+'''         `://-::.`                          `-++syhs` ''')
  print (default+'''          dNNNNNNNds-                      `odNNmddmm`''')
  print (default+'''          /mmmmdddmNdo-                   :hmdhhddmN+ ''')
  print (default+'''           /Nmmdddhhho++`     ''' +red+'WhoAmi'+default+'''     /hdhhhhhhdm-''')
  print (default+'''            hmdhhhyho/s/o.              /ddhhyyyyyhm:''')
  print (default+'''            omdyyyso/.-s/s.            .hhdyyyysssyho ''')
  print (default+'''            omdyyyys+-..o/s```..```.``.oddyyo+/:://oo`''')
  print (default+'''            /mddysss+::-.+y/``..``...`.ymhhho/:.-/+s/`''')
  print (default+'''            `+ddyyss/---.`sh.``-``...`.hdyyhssss+::::/++:`''')
  print (default+'''          -+syyyyyyy:oo:..-y: `````..``dsyyyyhhh/--:+sdNNm:''')
  print (default+'''        .smmdhysosyy.-:...-+y//``  ``:-mdhhhyyysoshddmmNNNN/''')
  print (default+'''        ymmdsyyyssso/::-:/+yNd/`     /dNNdyhhhhhshdmmmmmNMMm`''')
  print (default+'''       +mmmhosyyyys::+shdmNNd:`.-    ::sdddhddddhhdmmmmmNMN/''')
  print (default+'''       oNmmhyyyyhdhhhdhhs/+---``-` ``/.`-.:`:+odh+sydmNMNy-''')
  print (default+'''     ``.+mmmmddmmdysmh//-.:--.:.-....:-.---..........:+/-`''')
  print (default+'''       ..-ohNNNho::://::://+////::::::::::::-----.......`''')
  print (default+'''        `...---------:::::::::::::------------.......````''')
  print (default+'''           `````````````...........```````````````````'''     )

def banner_20():
  print (default+"  ``   ``  ``   ``  ``   ``  ``  ```  `` `-//ossyyyysso//-` ``  ```  ``  ``   ``  ``   ``  ``   ``"   )
  print ("``   ``  ``  ```  ``  ``   ``  ``   .:oymNNdhysoooooosyhdNNmyo:.   ``  ``   ``  ``  ```  ``  ``   ``"   )
  print ("  ``   ``  ``   ``  ``   ``  ``  .+hNNho:.```  ``  ``  ```.:ohmNh+.  ``  ``   ``  ``   ``  ``   ``  "   )
  print ("``   ``  ``   `   ``  ``   `` `/hNms:.` ``  ``.------.``  `` `.:smNh/` ``   ``  ``   `   ``  ``   ``"   )
  print ("   `   ``  ``   `        `  `+mNy:``   `-+shmNNmmddmmNNmhs+-`   ``:yNmo`  `        `   ``   `   `   "    )
  print ("  ``   ``  ``   ``  ``   ```yMy-``` `/ymNdy+:-.``````.-:+ydNmy/` ```-yMh```   ``  ``   ``  ``   ``  "    )
  print ("``   ``  ``  ``   ``  ``   .mM:`` -smNh/.``  ``  ``  ``   `./ymms- ``:Mm.   ``  ``   ``  ``  ``   ``"   )
  print ("  ``   ``  ``   ``  ``  ``` sMNyshNmo.``  ``   ``  ``   ``  ``.omNhshNMo ```  ``  ``   ``  ``   ``  "   )
  print ("``  ```  ``  ```  ``  ``  `+NN+ooo:.``  ``   ``  ``  ``   ``  ``.:+oo+NN+`  ``  ``  ```  ``  ```  ``"   )
  print ("  ``   ``  ``   ``  ``  ``+Nm:`  ```  ``  ``   ``  ``   ``  ``  ```  `:mN+``  ``  ``   ``  ``   ``  "   )
  print ("``  ```  ``  ```  ``  `` :NN:  ``   ``  ``   ``  ``  ``   ``  ``   ``  :NN: ``  ``  ```  ``  ``   ``"   )
  print ("  ``   ``  ``   ``  ``  .dM+ ``  ``   ``  ``   ``  ``   ``  ``   ``  `` +Md.  ``  ``   ``  ``   ``  "   )
  print ("``  ```  ``  ```  ``  ``+Md``  `-/+o+:. ``   ``  ``  ``   `` .:+++/-`  ``dM+``  ``  ``   ``  ```  ``"   )
  print ("  ``   ``  ``   ``  `` `hMo  `-hmdyyhmms. ``   ``  ``   `` .smmhyydmh-`  oMh` ``  ``   ``  ``   ``  "   )
  print ("                       `mM/`.:mM+.```.yMy`                `yMy.```.+Mm:.`/Mm`                       "   )
  print ("``  ```  ``   ``  ``  ``mMyhmmMN`   ``-NN-   ``  ``  ``   -NN-``   `NMmmhyMm``  ``  ``   ``  ```  ``"   )
  print ("  ``   ``  ``   ``  `` `dMNy:-NM-``   `hMo``   ``  ``   ``oMh`   ``-MN-/yNMd` ``  ``   ``  ``   ``  "    )
  print ("``  ```  ``  ```  ``  .yMMd`` yMs   `` +Md`  ``  ``  ``  `dM+ ``   sMy ``dMMy.  ``  ```  ``  ```  ``"   )
  print ("  ``   ``  ``   ``  ``yMhmN: `/Mm```  `-NN-`   ``  ``   `-NN-`  ```mM/` :NmhMy``  ``   ``  ``   ``  "   )
  print ("``  ```  ``  ```  `` -NN-+Md. `NM:  `` `hMo  ``  ``  ``  oMh` ``  :MN` .dM+-NN- ``  ```  ``  ```  ``"   )
  print ("  ``   ``  ``   ``  `/Md``sMh``yMs``  ``+Md`   ``  ``   `dM+``  ``sMy``hMs``dM/`  ``   ``  ``   ``  "   )
  print ("``  ```  ``  ```  `` :Mm. `+o` /Mm` ``  -NN- ``  ``  `` -NN-  `` `mM/ `o+` .mM: ``  ```  ``  ```  ``"   )
  print ("  ``   ``  ``   ``  ``hMo``  ```NM:   ```hMo   ``  ``   oMh```   :MN```  ``oMh``  ``   ``  ``   ``  "   )
  print ("``   ``  ``   ``  ``  .dMs.``   yMs ``  `+Md```  ``  ```dM+`  `` sMy   ``.sMd.  ``  ``   ``   `   ``"   )
  print ("     `    `   ``  `    .yNm+.`` :Mm``    .NN-    ``  ``-NN.    ``mM: ``.+mNy.   ``  ``   `    `   ` "   )
  print ("  ``   ``  ``   ``  ``  `-smNds+/NM:  `` `mM/  ``  ``  :Mm` ``  :MN/+sdNms-`  ``  ``   ``  ``   ``  "    )
  print ("``   ``  ``  ```  ``  ``   `:+yhdmMm/.``-yMh.``  ``  ``.hMy-``./mMmdhy+:`   ``  ``  ```  ``  ``   ``"   )
  print ("  ``   ``  ``   ``  ``   ``  ``  `:hNNmNNd+.   ``  ``   .+dNNmNNh:`  ``  ``   ``  ``   ``  ``   ``  "   )
  print ("``  ```  ``  ```  ``  ``   ``  ``   `....`   ``  ``  ``   `....`   ``  ``   ``  ``  ```  ``  ```  ``"   )


def banner_21():
  print (default+"               -`                                                      :`"                           )
  print ("               /`                                                      +   "                           )
  print ("               /`                                                     `+   "                            )
  print ("               /`                                                     .:  "                            )
  print ("               /`                                                     -:  "                              )
  print ("               +`                                                     -:  "                             )
  print ("               +`                                                     /-   "                           )
  print ("              `o-`                                                  -+yy:    "                        )
  print ("             `sdo-                                                  o`.`:/    "                        )
  print ("            `+-` /:                                                 +/:-/-     "                      )
  print ("            `++++s/.`                                           `-:+shddhyyyo/-.`    "                  )
  print ("         :+osydhydyo///-`                                    .::/+sss//o.so/oy+://.    "                 )
  print ("      .oy+//+o+--/ossy/oo:.                                ./--:++:+/./--`+o..oo.`//`   "                )
  print ("    -:+/`//+/.+`::s/++-./s/-`                             ::`::/-/:+ .:`+ `y/ .o+` -+`  "                )
  print ("  `+-o-`/./:-./ /y/:::s./////-                           ::`+-/-:-s.`-:.+``//  s::  :+  "               )
  print ("  /-+/`/./+o:/o-syy:`-/+`.:/:+-                         .o/o/oo/s/s:://:o-:/s//y+/::/s. "                )
  print (" `yoo/:o-+.+`-/`+:s/ `:s-.-s/+o`                        :+++:s/++:+-:/::+--/y--o/o:-./:  "              )
  print (" -:///+s++-+:/o:so/o--.//.`-/--.                        /-:-`/ :- +  -:.:  .s` /.+.  /:  "               )
  print (" :.:/`-:./ :`./ /--+//`./.:+/-.:                        +.:../ :. o  .:.-  .o` /./.  ::  "               )
  print (" +/o+.:/./ :`./ /-`::..:o-//s:`:                .       +.:-./ :. o  .:..  .o` /s++://:  "              )
  print (" ::++o+s++ :`./ ::`/-+--+ `-o/-/.....`...````` ./       +./.`: :. o  `/-.  .s` /:o+.::/   "              )
  print (" :-:/:-o:/ :`-+ ::`/:`  +`  +.`   `     `` `:/../:...   /./.`: :.`+  ./--  -y` /:o/.:+/`  "             )
  print (" :::o:-o+s`/.-/`:o//`  `o:../ooo/+:.........:+:/o+/::.  /./:.o://+y//+++o//+y+/yoo+./oy:--"            )
  print (" -/+yo+/os-o:/+-+/`/`   o-  :yo///`             ::.:`   :so++o.:.`+  ././  -y``+:o/+o/+::"              )
  print (" .yoso/s:o.+:-o/-..+----s+::+s/o-.                      ://o/o:+/-s--:o/o--/y--+:o:--+-"               )
  print (" `/ //`o.+-/:-o-.../:`  --  :+-o                        -:-:`+ -: o `./--  :s` /`+.  /`"               )
  print (" `/`/: / /.--:+.   :.   .: `-+:s                        -:./`+ :/:s:../:-  :s  +`+`  + "                )
  print ("  +.:/`+ -:.+/+++/::/-.`.:`.-o/s`                       .:`+`+..o//:o+/.-..sy-`o`+` `/ "               )
  print ("  /::s-o-//-+mmdMMMdyNdddsydNsdd/                       -: +.:-o+::/:-/``.+/.----s:`./ "              )
  print ("  -o-+.  -/`-sNdMMMmyMMMMNMMMhMMMm:                     -/-s//+:o:/-`.+..+o+o//`/o/.-:"                )
  print ("   -/o/-`.o .:oydNNNyMMMMMMMNs+NMMN.                    .+:o-`..s:/:::+-:::+/+-/so--o/"               )
  print ("       `.-::--/+/////++yNMMMM: sMMMo                       `.---+:---:+/+ooh+.+y+/-.` "              )
  print ("                        oMMMM: -MMMh                                         .-`  "                 )
  print ("     `:/:  ```          /MMMM.  hMMN.   "               )
  print ("    -+/:/-:-`:----      :MMMm`  :dh+`                                          ` .  `` "             )
  print ("   `o-:--:.:::---.``    :MMMm`   `y/+ooo/                                  .-:....-`. "             )
  print ("    s::::-::-::---.-`   `sso+`    `                                         `"                     )
  print ("     `+o+/--` ...        .yh`   "                         )
  print ("    ```.-```````````      -y-   "                           )
  print ("       ``````````          `oy.  "                         )



def banner_22():
  print (default +"""                        aa@@@@@@@@@@@@@aa              """)
  print (default +"""                     a@@@@@@@@@@@@@@@@@@@@@a              """)
  print (default +"""                   a@@@@@@@@@@@@@@@@@@@@@@@@@a              """)
  print (default +"""                  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""                 @@@@@@@~~~~@@@@@@@@@~~~~@@@@@@@              """)
  print (default +"""                 @@@@@@      @@@@@@@      @@@@@@              """)
  print (default +"""                 @@@@@@@aaaa@@@@@@@@@aaaa@@@@@@@              """)
  print (default +"""                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""                 `@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'              """)
  print (default +"""                  @@@@@@@@~@@@~@@@~@@@~@@@@@@@@              """)
  print (default +"""                   @@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""                    @@@@@@@@~@@@~@@@~@@@@@@@@              """)
  print (default +"""                     @@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""                      @@@@@@@@~@@@~@@@@@@@@              """)
  print (default +"""                       `@@@@@@@@@@@@@@@@@'              """)
  print (default +"""                           ~~@@@@@@@~~              """)



def banner_23():
  print (default +"""                        @@@              """)
  print (default +"""                        @@@              """)
  print (default +"""                         @@@              """)
  print (default +"""                         @@@              """)
  print (default +"""                 @@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""               @@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""           @@@@@@@@ @@@@@@@@@@@@@@@@ @@@@@@@@              """)
  print (default +"""         @@@@@@@@@   @@@@@@@@@@@@@@   @@@@@@@@@              """)
  print (default +"""       @@@@@@@@@@     @@@@@@@@@@@@     @@@@@@@@@@              """)
  print (default +"""      @@@@@@@@@@       @@@@  @@@@       @@@@@@@@@@              """)
  print (default +"""      @@@@@@@@@@@@@@@@@@@@    @@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""      @@@@@@@@@@@@@@@@@@        @@@@@@@@@@@@@@@@@@              """)
  print (default +"""      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""      @@@@@@@@@ @@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@              """)
  print (default +"""       @@@@@@@@  @@ @@ @@ @@ @@ @@ @@ @  @@@@@@@@              """)
  print (default +"""         @@@@@@@                        @@@@@@@              """)
  print (default +"""           @@@@@@  @@ @@ @@ @@ @@ @@ @ @@@@@@              """)
  print (default +"""            @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""               @@@@@@@@@@@@@@@@@@@@@@@@@@              """)
  print (default +"""                 @@@@@@@@@@@@@@@@@@@@@@              """)


def banner_24():
  print (default +'''                          ooo              ''')
  print (default +'''                         $ o$              ''')
  print (default +'''                        o $$              ''')
  print (default +'''              ""$$$    o" $$ oo "              ''')
  print (default +'''          " o$"$oo$$$"o$$o$$"$$$$$ o              ''')
  print (default +'''         $" "o$$$$$$o$$$$$$$$$$$$$$o     o              ''')
  print (default +'''      o$"    "$$$$$$$$$$$$$$$$$$$$$$o" "oo  o              ''')
  print (default +'''     " "     o  "$$$o   o$$$$$$$$$$$oo$$              ''')
  print (default +'''    " $     " "o$$$$$ $$$$$$$$$$$"$$$$$$$o              ''')
  print (default +'''  o  $       o o$$$$$"$$$$$$$$$$$o$$*""$$$$o " "              ''')
  print (default +''' o          o$$$$$"    "$$$$$$$$$$ "" oo $$   o $              ''')
  print (default +''' $  $       $$$$$  $$$oo "$$$$$$$$o o $$$o$$oo o o              ''')
  print (default +'''o        o $$$$$oo$$$$$$o$$$$ ""$$oo$$$$$$$$"  " "o              ''')
  print (default +'''"   o    $ ""$$$$$$$$$$$$$$  o  "$$$$$$$$$$$$   o "              ''')
  print (default +'''"   $      "$$$$$$$$$$$$$$   "   $$$"$$$$$$$$o  o              ''')
  print (default +'''$   o      o$"    "$$$$$$$$    oooo$$ $$$$$$$$"  "              ''')
  print (default +'''$      o""o $$o    $$$$$$$$$$$$$$$$$ ""  o$$$   $ o              ''')
  print (default +''' o     " "o "$$$$  $$$$$```````````` $  o$$$$$"" o o              ''')
  print (default +'''  " "  o  o$o" $$$$o   ""           o  o$$$$$"   o              ''')
  print (default +'''  $         o$$$$$$$oo            "oo$$$$$$$"    o              ''')
  print (default +'''  "$   o o$o $o o$$$$$"$$$$oooo$$$$$$$$$$$$$$"o$o              ''')
  print (default +'''    "o oo  $o$"oo$$$$$o$$$$$$$$$$$$"$$$$$$$$"o$"              ''')
  print (default +'''     "$ooo $$o$   $$$$$$$$$$$$$$$$ $$$$$$$$o"              ''')
  print (default +'''        "" $$$$$$$$$$$$$$$$$$$$$$"   ""              ''')
  print (default +'''                    y   ""+++++""              ''')


def banner_25():
  print (default +"""                             __        """)
  print (default +"""                            |  |        """)
  print (default +"""                            |  |         """)
  print (default +"""                        ___/____\___       """)
  print (default +"""                   _- ~              ~  _      """)
  print (default +"""                - ~                      ~ -_    """)
  print (default +"""              -                               _    """)
  print (default +"""            -         /\            /\          _   """)
  print (default +"""           -         / *\          / *\          _    """)
  print (default +"""          _         /____\        /____\          _    """)
  print (default +"""          _                  /\                   _    """)
  print (default +"""          _                 /__\                  _    """)
  print (default +"""          _      |\                      /|       _   """)
  print (default +"""           -     \ `\/\/\/\/\/\/\/\/\/\/' /      _     """)
  print (default +"""            -     \                      /      -     """)
  print (default +"""              ~    `\/^\/^\/^\/^\/^\/^\/'      ~    """)
  print (default +"""                ~                            -~    """)
  print (default +"""                 `--_._._._._._._._._._.._--'   """)

def banner_26():
  print (default +"""                            ........              """)
  print (default +"""                            ;::;;::;,              """)
  print (default +"""                            ;::;;::;;,              """)
  print (default +"""                           ;;:::;;::;;,              """)
  print (default +"""           .vnmmnv%vnmnv%,.;;;:::;;::;;,  .,vnmnv%vnmnv,   """)
  print (default +"""        vnmmmnv%vnmmmnv%vnmmnv%;;;;;;;%nmmmnv%vnmmnv%vnmmnv    """)
  print (default +"""      vnmmnv%vnmmmmmnv%vnmmmmmnv%;:;%nmmmmmmnv%vnmmmnv%vnmmmnv   """)
  print (default +"""     vnmmnv%vnmmmmmnv%vnmmmmmmmmnv%vnmmmmmmmmnv%vnmmmnv%vnmmmnv    """)
  print (default +"""    vnmmnv%vnmmmmmnv%vnmmmmmmmmnv%vnmmmmmmmmmmnv%vnmmmnv%vnmmmnv     """)
  print (default +"""   vnmmnv%vnmmmmmnv%vnmm;mmmmmmnv%vnmmmmmmmm;mmnv%vnmmmnv%vnmmmnv,   """)
  print (default +"""  vnmmnv%vnmmmmmnv%vnmm;  mmmmmnv%vnmmmmmmm;  mmnv%vnmmmnv%vnmmmnv    """)
  print (default +"""  vnmmnv%vnmmmmmnv%vn;;    mmmmnv%vnmmmmmm;;    nv%vnmmmmnv%vnmmmnv    """)
  print (default +""" vnmmnv%vnmmmmmmnv%v;;      mmmnv%vnmmmmm;;      v%vnmmmmmnv%vnmmmnv   """)
  print (default +""" vnmmnv%vnmmmmmmnv%vnmmmmmmmmm;;       mmmmmmmmmnv%vnmmmmmmnv%vnmmmnv   """)
  print (default +""" vnmmnv%vnmmmmmmnv%vnmmmmmmmmmm;;     mmmmmmmmmmnv%vnmmmmmmnv%vnmmmnv   """)
  print (default +""" vnmmnv%vnmmmmm nv%vnmmmmmmmmmmnv;, mmmmmmmmmmmmnv%vn;mmmmmnv%vnmmmnv   """)
  print (default +""" vnmmnv%vnmmmmm  nv%vnmmmmmmmmmnv%;nmmmmmmmmmmmnv%vn; mmmmmnv%vnmmmnv   """)
  print (default +""" `vnmmnv%vnmmmm,  v%vnmmmmmmmmmmnv%vnmmmmmmmmmmnv%v;  mmmmnv%vnnmmnv' """)
  print (default +"""  vnmmnv%vnmmmm;,   %vnmmmmmmmmmnv%vnmmmmmmmmmnv%;    mmmnv%vnmmmmnv  """)
  print (default +"""   vnmmnv%vnmmmm;;,   nmmm;,              mmmm;;     mmmnv%vnmmmmnv'""")
  print (default +"""   `vnmmnv%vnmmmmm;;,.         mmnv%v;,            mmmmnv%vnmmmmnv'""")
  print (default +"""    `vnmmnv%vnmmmmmmnv%vnmmmmmmmmnv%vnmmmmmmnv%vnmmmmmnv%vnmmmmnv' """)
  print (default +"""      `vnmvn%vnmmmmmmnv%vnmmmmmmmnv%vnmmmmmnv%vnmmmmmnv%vnmmmnv' """)
  print (default +"""          `vn%vnmmmmmmn%:%vnmnmmmmnv%vnmmmnv%:%vnmmnv%vnmnv' """)



def banner_27():
  print (default +""" ______________________________________________________________________________""")
  print (default +"""|                                                                              |""")
  print (default +"""|                          3Kom SuperHack II Logon                             |""")
  print (default +"""|______________________________________________________________________________|""")
  print (default +"""|                                                                              |""")
  print (default +"""|                                                                              |""")
  print (default +"""|                                                                              |""")
  print (default +"""|                 User Name:          [    """+red+"""WhoAmi"""+default+"""     ]                        |""")
  print (default +"""|                                                                              |""")
  print (default +"""|                 Password:           [               ]                        |""")
  print (default +"""|                                                                              |""")
  print (default +"""|                                                                              |""")
  print (default +"""|                                                                              |""")
  print (default +"""|                                   [ OK ]                                     |""")
  print (default +"""|______________________________________________________________________________|""")
  print (default +"""|                                                                              |""")
  print (default +"""|                                                        github://amerlaceset  |""")
  print (default +"""|______________________________________________________________________________|""")
  print ("")



def banner():
 e = str(random.randint(1,27))
 exec("banner_"+e+"()")
 sem()

