# all variable in module
all_var ={
    'rhosts'     : '192.168.1.1',
    'rports'     : '80',
    'url'        : 'http://examples.com',
    'username'   : 'anonymous',
    'listpass'   : 'waf/resources/pass.txt',
    'wordlist'   : 'waf/resources/pass.txt',
    'link'       : 'example.com',
    'apikey'     : 'bFWNo4jE90.....',
    'search'     : 'webcam',
    'lhost'      : '0.0.0.0',
    'lport'      : '8080',
    'ltype'      : 'unknown',
    'lname'      : 'payload',
    'ip'         : '192.168.1.1',
    'number'     : '12045152821',
    'interface'  : 'wlan0',
    'mode'       : 'unknown',
    'essid'      : 'freewifi',
    'bssid'      : '00:00:00:00:00:00',
    'channel'    : '11',
    'path'       : 'capture.cap',
    'dist'       : '0',
    'file'       : 'file',
    'bhaddr'     : '',
    'size'       : '600'
}
