# all variable in module
rhosts     = ["192.168.1.1"]
rports     = ["80"]
url        = ['http://examples.com']
username   = ['Anonymous']
listpass   = ['core/files/pass.txt']
link       = ['example.com']
Apikey     = ['bFWNo4jE90.....']
Search     = ['webcam']
lhost      = ["0.0.0.0"]
lport      = ["8080"]
ltype      = ["listen"]
lname      = ["payload"]
ip         = ["192.168.1.1"]
number     = ['12045152821']
